# Generated by Django 5.0.4 on 2024-04-23 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работ'},
        ),
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Описание деятельности'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Профиль'),
        ),
    ]
